### ISSUE TITLE
Doesn't insta-kill in Kunimitsu update.

### ISSUE THREAD

**Issue by BetterWaifus** [ien646/tekken_fth#3]

**Comment by Edgeexe** [comment]
Im trying to find HP address with no luck, as its the only thing needed for this to work

**Comment by ien646** [comment]
> 
> 
> Im trying to find the HP address with no luck, as its the only thing needed for this to work

Try disabling Fast Scan and drop the alignment to 1-2 bytes. Usually works for me.
I'll be trying myself in a few hours.

**Comment by Edgeexe** [comment]
> 
> 
> > Im trying to find the HP address with no luck, as its the only thing needed for this to work
> 
> Try disabling Fast Scan and drop the alignment to 1-2 bytes. Usually works for me.
> I'll be trying myself in a few hours.

Dropping the aligment did the trick, the new ID is 1434E4B36

**Comment by ien646** [comment]
Updated. I'll post a release in a moment.
