### ISSUE TITLE
it kills the player

### ISSUE THREAD

**Issue by etsiyo** [ien646/tekken_fth#6]
for some reason it kills me instead of the bot my dude

bruh i just want my watermelon bikini 💯 hahahaha

**Comment by ien646** [comment]
Play on left side

**Comment by Kozi801** [comment]
Hi,
Thank you for this project first and foremost. I am getting the same issue as the original poster. It occurs whether I pick the left or right side. 
1 open game
2 open cheat engine and select the tekken exe
3 go in treasure hunt pick side press pause before fight start
4 open the script and say yes and say enable
5 unpause

result
The bot kills me wheter left or right.
